

const shopItemsData = [
    {   
        id: 1,
        name: 'Qelem',
        price: 0.40,
        discount: 0.20,
        number: 0,
        color: '-',
        mark: 'Gigis',
        code: 9684,
        img: '../../img/products/qelem.png',
        addImg: '../../img/products/qelem2.jpg',
        outline: '/img/images/icons/heart-outline.png',
        filled: './img/images/icons/heart-filled.png',
        count: 1,
        cart: 'addPen',
        tag: 'Tövsiyə edilir'
    },
    {   
        id: 2,
        name: 'Qayci',
        price: 2.00,
        discount: 1.50,
        number: 0,
        color: '-',
        mark: 'Maped',
        code: 4682,
        img: '../../img/products/qayci.jpg',
        addImg: '../../img/products/qayci2.jpg',
        outline: '/img/images/icons/heart-outline.png',
        filled: './img/images/icons/heart-filled.png',
        count: 1,
        cart: 'addScissors',
        tag: 'Yeni'
    },
    {   
        id: 3,
        name: 'Textmarker',
        price: 0.60,
        discount: 0.30,
        number: 0,
        color: '-',
        mark: 'Grosso',
        code: 1235,
        img: '../../img/products/highlighter.jpg',
        addImg: '../../img/products/textmarker2.jpg',
        outline: '/img/images/icons/heart-outline.png',
        filled: './img/images/icons/heart-filled.png',
        count: 1,
        cart: 'addTextmarker'
    },
    {   
        id: 4,
        name: 'Stepler',
        price: 4.50,
        discount: 4.00,
        number: 0,
        color: '-',
        mark: 'Maped',
        code: 6743,
        img: '../../img/products/tikis.jpg',
        addImg: '../../img/products/stepler2.jpg',
        outline: '/img/images/icons/heart-outline.png',
        filled: './img/images/icons/heart-filled.png',
        count: 1,
        cart: 'addStepler'
    },
    {   
        id: 5,
        name: 'Tea',
        price: 2.40,
        discount: 2.00,
        number: 0,
        color: '-',
        mark: 'Ginger Mojito',
        code: 1237,
        img: '../../img/products/tess.jpg',
        addImg: '../../img/products/tess2.jpg',
        outline: '/img/images/icons/heart-outline.png',
        filled: './img/images/icons/heart-filled.png',
        count: 1,
        cart: 'addTea'
    },
    {   
        id: 6,
        name: 'Cookie',
        price: 3.50,
        discount: 3.00,
        number: 0,
        color: '-',
        mark: 'Adicto İntense',
        code: 1400,
        img: '../../img/products/adicto.png',
        addImg: '../../img/products/adicto2.png',
        outline: '/img/images/icons/heart-outline.png',
        filled: './img/images/icons/heart-filled.png',
        count: 1,
        cart: 'addCookie'
    },
    {   
        id: 7,
        name: 'Sugar',
        price: 2.60,
        discount: 2.00,
        number: 0,
        color: '-',
        mark: 'Azərşəkər',
        code: 7501,
        img: '../../img/products/kelleqend.jpg',
        addImg: '../../img/products/kelleqend2.jpg',
        outline: '/img/images/icons/heart-outline.png',
        filled: './img/images/icons/heart-filled.png',
        count: 1,
        cart: 'addSugar'
    },
    {   
        id: 8,
        name: 'Coffee',
        price: 3.50,
        discount: 3.00,
        number: 0,
        color: '-',
        mark: 'Mehmet efendi',
        code: 1298,
        img: '../../img/products/kahve.jpg',
        addImg: '../../img/products/kahve2.png',
        outline: '/img/images/icons/heart-outline.png',
        filled: './img/images/icons/heart-filled.png',
        count: 1,
        cart: 'addCoffee'
    }
]